### ISSUE TITLE
Hallo Wojciech.... m17enc: command not found

### ISSUE THREAD

**Issue by frank1562** [M17-Project/M17_RF_streamgen#1]
Please Wojciech, can you help me ?

pi@raspberrypi:~ $ rec -t raw -r 8000 --buffer 2048 -e signed-integer -b 16 -c 1 - | c2enc 3200 - - | m17enc DL1FROM DL1TO - out.raw
-bash: m17enc: command not found
rec WARN alsa: can't encode 0-bit Unknown or not applicable

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 8000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:00.77 [00:00:00.00] Out:4.10k [      |      ]        Clip:0    pi@raspberrypi:~ $ cd M17_RF_streamgen/

**Comment by sp5wwp** [comment]
This repo is obsolete.
